name: winwithfred
static_sites:
- name: winwithfred
  github:
    repo: WinWithFredToday/winwithfred
    branch: main
    deploy_on_push: true
  index_document: index.html
  catchall_document: 404-router.html
